### ISSUE TITLE
Solve 'Grasshopper - Debug'

### ISSUE THREAD

**Issue by odv** [js-mentorship-ramona/javascript#3]
https://www.codewars.com/kata/grasshopper-debug/train/javascript

**Comment by ConstantinRamona** [comment]
`function weatherInfo(temp) {
  let c = convertToCelsius(temp);
  if (c < 0){
    return(c + " is freezing temperature");
    }else{
    return(c + " is above freezing temperature");
  }
}

function convertToCelsius(fahrenheit) {
  let celsius = (fahrenheit - 32) * (5/9);
  return celsius;
}`
